---
# tasks file for subversion - EL Family

- name: EL Family | Installing {{ subversion_app }}
  ansible.builtin.yum:
    name: "{{ subversion_app }}"
    state: "{{ subversion_desired_state }}"
    update_cache: yes
